//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, type AttributeApplication, type FieldDefault, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "sqlite"
    } as const;
    models = {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("autoincrement") as FieldDefault
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                profile: {
                    name: "profile",
                    type: "Profile",
                    attributes: [{ name: "@json" }] as readonly AttributeApplication[]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                email: { type: "String" }
            }
        }
    } as const;
    typeDefs = {
        Profile: {
            name: "Profile",
            fields: {
                age: {
                    name: "age",
                    type: "Int"
                },
                gender: {
                    name: "gender",
                    type: "String",
                    optional: true
                },
                jobs: {
                    name: "jobs",
                    type: "Job",
                    optional: true,
                    array: true
                }
            }
        },
        Job: {
            name: "Job",
            fields: {
                company: {
                    name: "company",
                    type: "String"
                },
                title: {
                    name: "title",
                    type: "String"
                }
            }
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
